# docker-compose build
# docker-compose up --build

version: "3"
services:
    rbk:
        build: ./module_rbk
        image: module_rbk
        #volumes:
          #  - ./module_rbk:/tmp
        ports:
            - "8181:8081"
    weather:
        build: ./module_weather
        image: module_weather
        #volumes:
          #  - ./module_weather:/tmp
        ports:
            - "8182:8081"
    predict:
        build: ./module_predict
        image: module_predict
        #volumes:
        #    - ./module_predict:/tmp
        ports:
            - "8183:8081"
    db:
        image: nicolas/webdis
        ports:
            - "8184:7379"
    prometheus:
        image: prom/prometheus
        container_name: prometheus1
        volumes:
          - ./module_predict/env/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
          - 7091:9090

    grafana:
        image: grafana/grafana
        container_name: grafana1
        ports:
          - 2000:3000
        env_file:
          - ./module_predict/env/grafana.env
