# Load balance between replicas and nodes
# kubectl create -f service.yaml
# kubectl describe svc webapp1-svc
# kubectl describe ing ingress-tutorial
# kubectl expose deployment kube-boot --type=LoadBalancer --port=8081

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: webdis
    spec:
      containers:
      - name: webdis
        image: nicolas/webdis:latest
        ports:
        - containerPort: 7379
---
apiVersion: v1
kind: Service
metadata:
  name: webdis-svc
spec:
  ports:
    - port: 7379
      targetPort: 7379
  selector:
    app: webdis
  type: LoadBalancer
